# Generated by Django 5.0.7 on 2024-08-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='asettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_name', models.CharField(max_length=100)),
                ('a_logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('a_email', models.EmailField(max_length=100, unique=True)),
                ('a_phone', models.CharField(max_length=100)),
            ],
        ),
    ]
