# Generated by Django 5.0.7 on 2024-08-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0004_alter_product_image_product2'),
    ]

    operations = [
        migrations.AddField(
            model_name='asettings',
            name='add_logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
