# Generated by Django 5.0.7 on 2024-08-11 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0005_asettings_add_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asettings',
            name='add_logo',
        ),
    ]
