# Generated by Django 5.0.7 on 2024-08-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0007_ad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product2',
            old_name='image',
            new_name='image2',
        ),
        migrations.AlterField(
            model_name='ad',
            name='addlogo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/%Y/%m/%d/'),
        ),
    ]
