# Generated by Django 5.0.7 on 2024-08-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0008_rename_image_product2_image2_alter_ad_addlogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='agx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agxname', models.CharField(max_length=100)),
                ('agxlogo', models.ImageField(blank=True, null=True, upload_to='logo/%Y/%m/%d/')),
            ],
        ),
    ]
