# Generated by Django 5.0.7 on 2024-08-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0009_agx'),
    ]

    operations = [
        migrations.CreateModel(
            name='fo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foname', models.CharField(max_length=100)),
                ('fologo', models.ImageField(blank=True, null=True, upload_to='logo/%Y/%m/%d/')),
            ],
        ),
    ]
