# Generated by Django 5.0.7 on 2024-08-14 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0010_fo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fo',
        ),
    ]
