# Generated by Django 5.0.7 on 2024-08-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0012_fo'),
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('re_name', models.CharField(max_length=100)),
                ('re_logo', models.ImageField(blank=True, null=True, upload_to='logo/%Y/%m/%d/')),
                ('re_prof', models.CharField(max_length=100)),
                ('re_dep', models.TextField()),
            ],
        ),
    ]
