# Generated by Django 5.0.7 on 2024-08-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0013_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footaddress', models.CharField(max_length=100)),
                ('footemail', models.EmailField(max_length=254, unique=True)),
                ('footph', models.IntegerField()),
                ('we', models.ImageField(blank=True, null=True, upload_to='')),
                ('we1', models.ImageField(blank=True, null=True, upload_to='')),
                ('we2', models.ImageField(blank=True, null=True, upload_to='')),
                ('we3', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
