# Generated by Django 5.0.7 on 2024-08-16 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0014_footer'),
    ]

    operations = [
        migrations.CreateModel(
            name='two',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twon', models.CharField(max_length=100)),
                ('twoim', models.ImageField(blank=True, null=True, upload_to='')),
                ('twopr', models.IntegerField()),
            ],
        ),
    ]
