# Generated by Django 5.0.7 on 2024-09-08 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0015_two'),
    ]

    operations = [
        migrations.AlterField(
            model_name='two',
            name='twopr',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
